#!/usr/bin/env node
/**
 * verify-corpus.mjs — the build gate.
 *
 * Plain Node ESM, zero dependencies, read-only except for the counts and hash it
 * writes back into data/corpus/meta.json. Safe to re-run. Every failure names the
 * file, the record and the field, so the fix is obvious rather than archaeological.
 *
 *   node scripts/verify-corpus.mjs            C1-C7, C9 (source), C10-C14
 *   node scripts/verify-corpus.mjs --built    adds C8 and C9 over emitted HTML and the résumé PDF
 *   node scripts/verify-corpus.mjs --strict    turns C11 staleness warnings into failures
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SCAN SCOPE — read this before adding a directory
 * ─────────────────────────────────────────────────────────────────────────────
 * The numeric gate (C8) and the retraction gate (C9) run over the NEW surfaces
 * only: the emitted Next.js HTML and the hand-authored source that feeds it.
 *
 * `public/docs/**` is deliberately EXCLUDED. Those are frozen legacy pages,
 * preserved byte-for-byte because live URLs point at them from a résumé and from
 * LinkedIn, and they are full of exactly the figures this corpus retracts. Scanning
 * them would produce a build that can never go green, and a gate that can never
 * pass is a gate that gets deleted. They are covered instead by the migration's own
 * URL-and-byte-size harness, which asserts they have not changed.
 *
 * The two exceptions inside that directory are files this corpus OWNS, and they
 * are scanned:
 *   public/docs/resume_content.html   generated by scripts/gen-resume.mjs
 *   public/docs/Resume.pdf            scanned as extracted text (see C9)
 *
 * `data/corpus/**` is also excluded from the bulk C9 scan, for the obvious reason:
 * the retraction records quote the strings they forbid. Instead, C9 scans the three
 * corpus fields that are actually SPOKEN — a gap's honestAnswer, a dispute's
 * agentGuidance, and a requirement's fallback — because those reach a reader.
 */

import {
  readFileSync,
  writeFileSync,
  existsSync,
  readdirSync,
} from 'node:fs'
import { resolve, dirname, join, relative, extname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CORPUS = join(ROOT, 'data', 'corpus')
const SCHEMAS = join(CORPUS, 'schemas')

const argv = process.argv.slice(2)
const BUILT = argv.includes('--built')
const STRICT = argv.includes('--strict')
const QUIET = argv.includes('--quiet')

const failures = []
const warnings = []
const fail = (check, where, msg) => failures.push({ check, where, msg })
const warn = (check, where, msg) => warnings.push({ check, where, msg })

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'))

/* ═══════════════════════════════════════════════════════════════════════════
   A small JSON Schema evaluator.
   Only the keywords this corpus actually uses, implemented honestly rather than
   approximated: type, required, additionalProperties, properties, items, enum,
   const, pattern, minLength/maxLength, minItems/maxItems, minimum/maximum,
   format:"date", and allOf with if/then. Anything unrecognised is reported rather
   than ignored, so a schema keyword that silently does nothing cannot creep in.
   ═══════════════════════════════════════════════════════════════════════════ */

const KNOWN = new Set([
  '$schema', '$id', 'title', 'description', '$defs', 'note',
  'type', 'required', 'additionalProperties', 'properties', 'items',
  'enum', 'const', 'pattern', 'minLength', 'maxLength', 'minItems', 'maxItems',
  'minimum', 'maximum', 'format', 'allOf', 'if', 'then',
])

const typeOf = (v) =>
  v === null ? 'null' : Array.isArray(v) ? 'array' : Number.isInteger(v) ? 'integer' : typeof v

function typeMatches(value, expected) {
  const actual = typeOf(value)
  const list = Array.isArray(expected) ? expected : [expected]
  return list.some((t) =>
    t === 'number' ? actual === 'number' || actual === 'integer' : t === actual
  )
}

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/

function validate(schema, value, path, out) {
  for (const key of Object.keys(schema)) {
    if (!KNOWN.has(key)) out.push(`${path}: schema uses unsupported keyword "${key}"`)
  }

  if (schema.type !== undefined && !typeMatches(value, schema.type)) {
    out.push(`${path}: expected type ${JSON.stringify(schema.type)}, got ${typeOf(value)}`)
    return
  }
  if (schema.enum && !schema.enum.includes(value)) {
    out.push(`${path}: ${JSON.stringify(value)} is not one of ${JSON.stringify(schema.enum)}`)
  }
  if (schema.const !== undefined && value !== schema.const) {
    out.push(`${path}: expected constant ${JSON.stringify(schema.const)}, got ${JSON.stringify(value)}`)
  }

  if (typeof value === 'string') {
    if (schema.pattern && !new RegExp(schema.pattern).test(value)) {
      out.push(`${path}: ${JSON.stringify(value.slice(0, 60))} does not match /${schema.pattern}/`)
    }
    if (schema.minLength !== undefined && value.length < schema.minLength) {
      out.push(`${path}: length ${value.length} is below minLength ${schema.minLength}`)
    }
    if (schema.maxLength !== undefined && value.length > schema.maxLength) {
      out.push(`${path}: length ${value.length} exceeds maxLength ${schema.maxLength}`)
    }
    if (schema.format === 'date' && !DATE_RE.test(value)) {
      out.push(`${path}: ${JSON.stringify(value)} is not an ISO date (YYYY-MM-DD)`)
    }
  }

  if (typeof value === 'number') {
    if (schema.minimum !== undefined && value < schema.minimum) {
      out.push(`${path}: ${value} is below minimum ${schema.minimum}`)
    }
    if (schema.maximum !== undefined && value > schema.maximum) {
      out.push(`${path}: ${value} exceeds maximum ${schema.maximum}`)
    }
  }

  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems) {
      out.push(`${path}: ${value.length} item(s), minItems is ${schema.minItems}`)
    }
    if (schema.maxItems !== undefined && value.length > schema.maxItems) {
      out.push(`${path}: ${value.length} item(s), maxItems is ${schema.maxItems}`)
    }
    if (schema.items) {
      value.forEach((item, i) => validate(schema.items, item, `${path}/${i}`, out))
    }
  }

  if (value && typeof value === 'object' && !Array.isArray(value)) {
    for (const key of schema.required ?? []) {
      if (!(key in value)) out.push(`${path}: missing required property "${key}"`)
    }
    if (schema.additionalProperties === false && schema.properties) {
      for (const key of Object.keys(value)) {
        if (!(key in schema.properties)) out.push(`${path}: unexpected property "${key}"`)
      }
    }
    for (const [key, sub] of Object.entries(schema.properties ?? {})) {
      if (key in value) validate(sub, value[key], `${path}/${key}`, out)
    }
  }

  for (const sub of schema.allOf ?? []) {
    if (sub.if) {
      const probe = []
      validate(sub.if, value, path, probe)
      if (probe.length === 0 && sub.then) validate(sub.then, value, path, out)
    } else {
      validate(sub, value, path, out)
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   Load everything.
   ═══════════════════════════════════════════════════════════════════════════ */

const FILES = {
  claims: 'claims.json',
  sources: 'sources.json',
  orgs: 'orgs.json',
  people: 'people.json',
  roles: 'roles.json',
  artifacts: 'artifacts.json',
  concepts: 'concepts.json',
  skills: 'skills.json',
  gaps: 'gaps.json',
  disputes: 'disputes.json',
  retractions: 'retractions.json',
  roleProfiles: 'role-profiles.json',
  allowedNumbers: 'allowed-non-claim-numbers.json',
  meta: 'meta.json',
}

const data = {}
for (const [key, file] of Object.entries(FILES)) {
  const p = join(CORPUS, file)
  if (!existsSync(p)) {
    fail('C1', file, 'file is missing from data/corpus/')
    continue
  }
  try {
    data[key] = readJson(p)
  } catch (err) {
    fail('C1', file, `is not valid JSON: ${err.message}`)
  }
}

const snapshotPath = join(CORPUS, 'fischer-snapshot.json')
const snapshot = existsSync(snapshotPath) ? readJson(snapshotPath) : null

if (failures.length) {
  report()
  process.exit(1)
}

const claimById = new Map(data.claims.map((c) => [c.id, c]))
const byId = {
  src: new Set(data.sources.map((s) => s.id)),
  org: new Set(data.orgs.map((o) => o.id)),
  per: new Set(data.people.map((p) => p.id)),
  rol: new Set(data.roles.map((r) => r.id)),
  art: new Set(data.artifacts.map((a) => a.id)),
  cpt: new Set(data.concepts.map((c) => c.id)),
  skl: new Set(data.skills.map((s) => s.id)),
  gap: new Set(data.gaps.map((g) => g.id)),
  dsp: new Set(data.disputes.map((d) => d.id)),
  ret: new Set(data.retractions.map((r) => r.id)),
  clm: new Set(data.claims.map((c) => c.id)),
  rp: new Set(data.roleProfiles.map((p) => p.id)),
}

/* ═══════════════════════════════════════════════════════════════════════════
   C1 — schema validation
   ═══════════════════════════════════════════════════════════════════════════ */

{
  const claimSchema = readJson(join(SCHEMAS, 'claim.schema.json'))
  const sourceSchema = readJson(join(SCHEMAS, 'source.schema.json'))
  const retractionSchema = readJson(join(SCHEMAS, 'retraction.schema.json'))
  const misc = readJson(join(SCHEMAS, 'misc.schema.json'))

  const pairs = [
    ['claims.json', claimSchema, data.claims],
    ['sources.json', sourceSchema, data.sources],
    ['retractions.json', retractionSchema, data.retractions],
    ['orgs.json', misc.$defs.org, data.orgs],
    ['people.json', misc.$defs.person, data.people],
    ['roles.json', misc.$defs.role, data.roles],
    ['artifacts.json', misc.$defs.artifact, data.artifacts],
    ['concepts.json', misc.$defs.concept, data.concepts],
    ['skills.json', misc.$defs.skill, data.skills],
    ['gaps.json', misc.$defs.gap, data.gaps],
    ['disputes.json', misc.$defs.dispute, data.disputes],
    ['role-profiles.json', misc.$defs.roleProfile, data.roleProfiles],
    ['allowed-non-claim-numbers.json', misc.$defs.allowedNumber, data.allowedNumbers],
    ['meta.json', misc.$defs.meta, data.meta],
  ]
  if (snapshot) pairs.push(['fischer-snapshot.json', misc.$defs.fischerSnapshot, snapshot])

  for (const [file, schema, value] of pairs) {
    const out = []
    validate(schema, value, '#', out)
    for (const message of out) fail('C1', file, message)
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C2 — status invariants
   ═══════════════════════════════════════════════════════════════════════════ */

for (const c of data.claims) {
  if (c.status === 'disputed') {
    if (c.asserted) fail('C2', `claims.json#${c.id}`, 'status is "disputed" but asserted is true')
    if (!c.disputeId) fail('C2', `claims.json#${c.id}`, 'status is "disputed" with no disputeId')
    if (c.surfaces.some((s) => s !== 'internal')) {
      fail('C2', `claims.json#${c.id}`, `disputed claim is licensed for ${c.surfaces.join(', ')} — only "internal" is allowed`)
    }
  }
  if (c.kind === 'metric' && !c.value) {
    fail('C2', `claims.json#${c.id}`, 'kind is "metric" with no value block')
  }
  if (c.kind !== 'metric' && c.value) {
    fail('C2', `claims.json#${c.id}`, `kind is "${c.kind}" but carries a value block — only metrics may`)
  }
}

// Every id namespace is unique across the whole corpus.
{
  const seen = new Map()
  const all = [
    ...data.claims, ...data.sources, ...data.orgs, ...data.people, ...data.roles,
    ...data.artifacts, ...data.concepts, ...data.skills, ...data.gaps,
    ...data.disputes, ...data.retractions, ...data.roleProfiles,
  ]
  for (const rec of all) {
    if (seen.has(rec.id)) fail('C2', rec.id, 'duplicate id in the corpus')
    seen.set(rec.id, true)
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C3 — referential integrity, in both directions
   ═══════════════════════════════════════════════════════════════════════════ */

function refs(where, ids, prefix, field) {
  for (const id of ids ?? []) {
    if (!byId[prefix].has(id)) fail('C3', where, `${field} points at "${id}", which does not exist`)
  }
}

for (const c of data.claims) {
  const where = `claims.json#${c.id}`
  const subjectPrefix = c.subject.split(':')[0]
  if (!byId[subjectPrefix] || !byId[subjectPrefix].has(c.subject)) {
    fail('C3', where, `subject "${c.subject}" does not resolve`)
  }
  refs(where, c.sources, 'src', 'sources')
  refs(where, c.concepts, 'cpt', 'concepts')
  refs(where, c.skills, 'skl', 'skills')
  refs(where, c.artifacts, 'art', 'artifacts')
  refs(where, c.caveats, 'clm', 'caveats')
  refs(where, c.derivedFrom, 'clm', 'derivedFrom')
  if (c.disputeId) refs(where, [c.disputeId], 'dsp', 'disputeId')
}

for (const s of data.skills) {
  refs(`skills.json#${s.id}`, s.groundedIn, 'clm', 'groundedIn')
  refs(`skills.json#${s.id}`, s.concepts, 'cpt', 'concepts')
}
for (const g of data.gaps) {
  refs(`gaps.json#${g.id}`, g.concepts, 'cpt', 'concepts')
  refs(`gaps.json#${g.id}`, g.nearestEvidence, 'clm', 'nearestEvidence')
}
for (const d of data.disputes) {
  refs(`disputes.json#${d.id}`, d.positions.map((p) => p.sourceId), 'src', 'positions[].sourceId')
  refs(`disputes.json#${d.id}`, d.blocksClaims, 'clm', 'blocksClaims')
}
for (const r of data.retractions) {
  refs(`retractions.json#${r.id}`, r.supersededBy, 'clm', 'supersededBy')
  const subjectPrefix = r.subject.split(':')[0]
  if (!byId[subjectPrefix] || !byId[subjectPrefix].has(r.subject)) {
    fail('C3', `retractions.json#${r.id}`, `subject "${r.subject}" does not resolve`)
  }
  for (const p of r.forbiddenPatterns ?? []) {
    try {
      new RegExp(p.source, p.flags)
    } catch (err) {
      fail('C3', `retractions.json#${r.id}`, `forbiddenPattern is not a valid regex: ${err.message}`)
    }
  }
}
for (const c of data.concepts) {
  refs(`concepts.json#${c.id}`, c.adjacent.map((a) => a.id), 'cpt', 'adjacent[].id')
  if (c.negativeGapId) refs(`concepts.json#${c.id}`, [c.negativeGapId], 'gap', 'negativeGapId')
}
for (const a of data.artifacts) {
  if (a.roleId) refs(`artifacts.json#${a.id}`, [a.roleId], 'rol', 'roleId')
  if (a.access === 'public' && !a.url) {
    fail('C3', `artifacts.json#${a.id}`, 'access is "public" but url is null')
  }
  if (a.access !== 'public' && a.url) {
    fail('C3', `artifacts.json#${a.id}`, `access is "${a.access}" but a url is set — a non-public artifact must not be linked`)
  }
}
for (const r of data.roles) {
  refs(`roles.json#${r.id}`, [r.orgId], 'org', 'orgId')
  refs(`roles.json#${r.id}`, r.advisorIds, 'per', 'advisorIds')
  // `ongoing` means "has not finished", which is compatible with an EXPECTED end
  // date in the future — a degree in progress has both. What it is not compatible
  // with is an end date that has already passed: that is a role the corpus is
  // still describing in the present tense after it stopped.
  if (r.ongoing === true && r.period.end !== null) {
    const [ey, em] = r.period.end.split('-')
    const end = new Date(Number(ey), em ? Number(em) - 1 : 11, 28)
    if (end < new Date()) {
      fail(
        'C3',
        `roles.json#${r.id}`,
        `ongoing is true but period.end (${r.period.end}) is in the past — either the role ended, or the end date is stale`
      )
    }
  }
}
for (const o of data.orgs) {
  if (o.parentOrgId) refs(`orgs.json#${o.id}`, [o.parentOrgId], 'org', 'parentOrgId')
}
for (const p of data.people) refs(`people.json#${p.id}`, [p.orgId], 'org', 'orgId')
for (const profile of data.roleProfiles) {
  for (const req of profile.requirements) {
    const where = `role-profiles.json#${profile.id}/${req.id}`
    refs(where, req.concepts, 'cpt', 'concepts')
    refs(where, req.pinned, 'clm', 'pinned')
    for (const id of req.pinned) {
      const claim = claimById.get(id)
      if (claim && !claim.surfaces.includes('agent')) {
        fail('C3', where, `pinned claim ${id} is not licensed for the "agent" surface, so the scorer can never return it`)
      }
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C4 — in-progress work stays in progress
   ═══════════════════════════════════════════════════════════════════════════ */

/**
 * A completion verb that is NOT negated. The negation window matters: the single
 * most important sentence in this group is "this work is in flight and not
 * shipped", and a rule that forbids the word "shipped" outright would forbid the
 * exact sentence it exists to protect. So the lookbehind lets a negation through
 * and catches the bare assertion.
 */
const NEGATED = /\b(?:not|never|isn't|isn t|is not|aren't|are not|yet to be|rather than|instead of|no)\b[\s\w]{0,24}$/i
const COMPLETION_VERBS = /\b(built|shipped|deployed|delivered|launched|completed|finished)\b/gi

for (const c of data.claims) {
  if (c.status !== 'in-progress') continue
  if (c.tense !== 'present-progressive') {
    fail('C4', `claims.json#${c.id}`, `status is "in-progress" but tense is "${c.tense}"`)
  }
  const outsideQuotes = c.statement.replace(/"[^"]*"/g, ' ')
  let hit = null
  for (const m of outsideQuotes.matchAll(COMPLETION_VERBS)) {
    if (!NEGATED.test(outsideQuotes.slice(0, m.index))) {
      hit = m
      break
    }
  }
  if (hit) {
    fail(
      'C4',
      `claims.json#${c.id}`,
      `statement uses the completion verb "${hit[0]}" outside a quotation. In-progress work must not read as finished — rewrite in the present progressive.`
    )
  }
  if (c.reviewEvery > 180) {
    fail('C4', `claims.json#${c.id}`, `in-progress claims need reviewEvery <= 180 (the tense goes stale fastest); found ${c.reviewEvery}`)
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C5 — a narrative may combine claims; it may not add a fact
   ═══════════════════════════════════════════════════════════════════════════ */

for (const c of data.claims) {
  if (c.kind !== 'narrative') continue
  if (!c.derivedFrom || c.derivedFrom.length === 0) {
    fail('C5', `claims.json#${c.id}`, 'kind is "narrative" with an empty derivedFrom')
    continue
  }
  for (const id of c.derivedFrom) {
    const parent = claimById.get(id)
    if (parent && !parent.asserted) {
      fail('C5', `claims.json#${c.id}`, `derivedFrom includes ${id}, which is not asserted — a narrative may not rest on a claim we decline to make`)
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C6 — every verificationPath resolves
   ═══════════════════════════════════════════════════════════════════════════ */

const REPO_PREFIXES = ['public/', 'backend/', 'data/', 'lib/', 'scripts/', 'app/', 'components/', 'tests/']

/**
 * Resolve an absolute path written inside a human-readable locator.
 *
 * These strings are meant to be read as much as parsed — they carry line
 * references, em-dash commentary, a second path after "and", and filenames with
 * parentheses in them. Rather than impose a machine-friendly format on a field
 * whose whole purpose is to be followed by a person, try the plausible
 * truncations longest-first and accept the first that exists on disk.
 */
function resolveLocalPath(raw) {
  const stripLineRefs = (s) => s.replace(/:[0-9L][-0-9,L\s:]*$/, '').trim()
  let candidate = raw.split(' and /')[0].split(' —')[0].trim()

  // Trim word by word from the right, trying the line-reference-stripped form at
  // each step. This survives filenames containing spaces AND trailing prose,
  // neither of which a single split can handle.
  while (candidate.length > 1) {
    if (candidate.startsWith('/') && existsSync(candidate)) return candidate
    const stripped = stripLineRefs(candidate)
    if (stripped !== candidate && stripped.startsWith('/') && existsSync(stripped)) return stripped
    const cut = candidate.lastIndexOf(' ')
    if (cut <= 0) break
    candidate = candidate.slice(0, cut).trim()
  }
  return null
}

function checkVerificationPath(where, raw) {
  const path = String(raw).trim()

  if (/^https?:\/\//.test(path)) {
    // Format only, never a network call. A gate that depends on the internet is
    // a gate that fails for reasons unrelated to the thing it checks, and a
    // flaky gate gets disabled — which is strictly worse than a warning.
    try {
      new URL(path.split(' ')[0])
    } catch {
      fail('C6', where, `verificationPath looks like a URL but does not parse: ${path.slice(0, 80)}`)
    }
    return
  }

  if (path.startsWith('git show ')) {
    const m = /^git show ([0-9a-f]{7,40}):(\S+)/.exec(path)
    if (!m) fail('C6', where, `git verificationPath must read "git show <ref>:<path>": ${path.slice(0, 80)}`)
    return
  }

  if (path.startsWith('/')) {
    // An owner-archive path: outside both repositories, so CI cannot see it.
    // Warn, never fail — same reasoning as the barn-owl refresh script.
    if (!resolveLocalPath(path)) {
      warn('C6', where, `owner-archive path is not present on this machine: ${path.slice(0, 110)}`)
    }
    return
  }

  if (path.startsWith('sqlite3 ') || path.startsWith('find ') || path.startsWith('git -C ')) {
    return // a reproducible command, checked by running it, not by stat()
  }

  if (REPO_PREFIXES.some((p) => path.startsWith(p))) {
    const file = path.split(':L')[0].split(' —')[0].split(' (')[0].trim()
    if (!existsSync(join(ROOT, file))) {
      fail('C6', where, `repo path does not exist: ${file}`)
    }
    return
  }

  // Anything else is prose (a brief citation, an archive description). Allowed,
  // but it must at least be long enough to be followed by a human.
  if (path.length < 20) {
    fail('C6', where, `verificationPath is neither a path, a URL, a git object nor a followable description: ${JSON.stringify(path)}`)
  }
}

for (const c of data.claims) checkVerificationPath(`claims.json#${c.id}`, c.verificationPath)

for (const s of data.sources) {
  if (s.kind === 'repo-file' && s.repo === 'target') {
    const file = s.locator.startsWith('/') ? s.locator : join(ROOT, s.locator)
    if (!existsSync(file)) fail('C6', `sources.json#${s.id}`, `repo-file locator does not exist: ${s.locator}`)
  }
  if (s.kind === 'owner-archive' && !resolveLocalPath(s.locator)) {
    warn('C6', `sources.json#${s.id}`, `owner-archive locator is not present on this machine: ${s.locator.slice(0, 110)}`)
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C12 — every legacy URL keeps resolving
   ═══════════════════════════════════════════════════════════════════════════ */

for (const a of data.artifacts) {
  if (!a.legacyPath) continue
  if (!existsSync(join(ROOT, a.legacyPath))) {
    fail('C12', `artifacts.json#${a.id}`, `legacyPath does not exist on disk: ${a.legacyPath}. Every path here is a live URL on a résumé domain.`)
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C7 / C10 — surface licensing and mandatory caveats, over hand-authored source
   ═══════════════════════════════════════════════════════════════════════════ */

const SOURCE_DIRS = ['content', 'app', 'components', 'lib']
const SOURCE_EXCLUDE = [join(ROOT, 'lib', 'corpus'), join(ROOT, 'node_modules'), join(ROOT, '.next')]

function walk(dir, exts, exclude = []) {
  const out = []
  if (!existsSync(dir)) return out
  const stack = [dir]
  while (stack.length) {
    const cur = stack.pop()
    if (exclude.some((e) => cur === e || cur.startsWith(e + '/'))) continue
    let entries
    try {
      entries = readdirSync(cur, { withFileTypes: true })
    } catch {
      continue
    }
    for (const e of entries) {
      const p = join(cur, e.name)
      if (e.isDirectory()) stack.push(p)
      else if (e.isFile() && exts.includes(extname(e.name))) out.push(p)
    }
  }
  return out
}

const sourceFiles = SOURCE_DIRS.flatMap((d) =>
  walk(join(ROOT, d), ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.json', '.md'], SOURCE_EXCLUDE)
)

const CLAIM_REF = /\bclm:[a-z0-9]+(?:-[a-z0-9]+)*\b/g
const SURFACE_HINT = /['"](page|resume|jsonld|agent)['"]/

for (const file of sourceFiles) {
  const text = readFileSync(file, 'utf8')
  const rel = relative(ROOT, file)
  const referenced = new Set(text.match(CLAIM_REF) ?? [])
  if (!referenced.size) continue

  // Which surface is this file rendering? Inferred from the directory, with an
  // explicit surface literal in the file as an override. If we cannot tell, we
  // check existence only — a wrong guess would be worse than no guess.
  let surface = null
  if (rel.startsWith('app/resume')) surface = 'resume'
  else if (rel.startsWith('lib/seo')) surface = 'jsonld'
  else if (rel.startsWith('lib/agent')) surface = 'agent'
  else if (rel.startsWith('content') || rel.startsWith('app') || rel.startsWith('components')) surface = 'page'
  const explicit = SURFACE_HINT.exec(text)
  if (explicit) surface = explicit[1]

  for (const id of referenced) {
    const claim = claimById.get(id)
    if (!claim) {
      fail('C7', rel, `references claim "${id}", which does not exist in the corpus`)
      continue
    }
    if (!claim.asserted) {
      fail('C7', rel, `references ${id}, which is asserted:false and must never be rendered`)
      continue
    }
    if (surface && !claim.surfaces.includes(surface)) {
      fail('C7', rel, `references ${id} on surface "${surface}", which it is not licensed for (licensed: ${claim.surfaces.join(', ')})`)
    }
    for (const caveatId of claim.caveats ?? []) {
      if (!referenced.has(caveatId)) {
        fail(
          'C10',
          rel,
          `renders ${id} without its mandatory caveat ${caveatId}. That caveat is not advisory — it is the sentence that keeps the claim from being read as something it is not.`
        )
      }
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C9 — the retraction gate
   ═══════════════════════════════════════════════════════════════════════════ */

const matchers = []
for (const r of data.retractions) {
  for (const phrase of r.forbiddenPhrases) {
    matchers.push({
      id: r.id,
      label: phrase,
      re: new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'),
      sayInstead: r.supersededBy ?? [],
    })
  }
  for (const p of r.forbiddenPatterns ?? []) {
    matchers.push({
      id: r.id,
      label: `/${p.source}/`,
      re: new RegExp(p.source, p.flags || 'i'),
      sayInstead: r.supersededBy ?? [],
    })
  }
}

function scanForRetractions(where, text, check = 'C9') {
  for (const m of matchers) {
    const hit = m.re.exec(text)
    if (!hit) continue
    const at = text.indexOf(hit[0])
    const context = text.slice(Math.max(0, at - 50), at + hit[0].length + 50).replace(/\s+/g, ' ')
    fail(
      check,
      where,
      `contains retracted content "${hit[0]}" (${m.id}) — "…${context}…"` +
        (m.sayInstead.length ? ` Say ${m.sayInstead.join(' / ')} instead.` : ' There is no replacement: it does not ship.')
    )
  }
}

// The three corpus fields that are actually SPOKEN to a reader.
for (const g of data.gaps) scanForRetractions(`gaps.json#${g.id}/honestAnswer`, g.honestAnswer)
for (const d of data.disputes) scanForRetractions(`disputes.json#${d.id}/agentGuidance`, d.agentGuidance)
for (const p of data.roleProfiles) {
  for (const req of p.requirements) {
    if (req.fallback) scanForRetractions(`role-profiles.json#${p.id}/${req.id}/fallback`, req.fallback)
  }
}
// And every sentence a claim licenses.
for (const c of data.claims) {
  scanForRetractions(`claims.json#${c.id}/statement`, c.statement)
  scanForRetractions(`claims.json#${c.id}/short`, c.short)
  if (c.value) scanForRetractions(`claims.json#${c.id}/value.display`, c.value.display)
}
// And the hand-authored source that renders them.
for (const file of sourceFiles) {
  scanForRetractions(relative(ROOT, file), readFileSync(file, 'utf8'))
}

/* ═══════════════════════════════════════════════════════════════════════════
   C13 — the ongoing barn-owl work carries a verification date
   ═══════════════════════════════════════════════════════════════════════════ */

const LIVE_SUBJECTS = new Set(
  data.roles.filter((r) => r.ongoing === true).map((r) => r.id)
)

for (const c of data.claims) {
  if (!LIVE_SUBJECTS.has(c.subject)) continue
  if (!c.verifiedOn) {
    fail(
      'C13',
      `claims.json#${c.id}`,
      `is about an ongoing role (${c.subject}) and carries no verifiedOn. Work that is still moving needs a date on every figure.`
    )
  }
}

// A figure DERIVED FROM THE LIVE SYSTEM must be covered by the refresh script, or
// it is a number nobody can re-derive — the one thing this corpus is not allowed
// to have. Scoped by SOURCE rather than by subject: a barn-owl metric that comes
// from the résumé or from a dated audit report is fixed in time and does not move,
// so demanding a re-query for it would be theatre.
const LIVE_SOURCES = new Set(['src:iccl-db', 'src:iccl-raw-archive'])
{
  const refreshScript = join(ROOT, 'scripts', 'corpus-refresh-fischer.mjs')
  const refreshText = existsSync(refreshScript) ? readFileSync(refreshScript, 'utf8') : ''
  for (const c of data.claims) {
    if (c.kind !== 'metric') continue
    if (!c.sources.some((s) => LIVE_SOURCES.has(s))) continue
    if (!refreshText.includes(c.id)) {
      fail(
        'C13',
        `claims.json#${c.id}`,
        'is derived from a live system (the lab database or its raw archive) and scripts/corpus-refresh-fischer.mjs does not cover it. Add it to that script\'s PUBLISHED table so the figure can be re-derived, or the claim is unverifiable in practice.'
      )
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C14 — the TypeScript mirror still matches the schemas
   ═══════════════════════════════════════════════════════════════════════════ */

{
  const typesPath = join(ROOT, 'lib', 'corpus', 'types.ts')
  if (!existsSync(typesPath)) {
    fail('C14', 'lib/corpus/types.ts', 'is missing — the compile-time mirror of the schemas')
  } else {
    const types = readFileSync(typesPath, 'utf8')
    const claimSchema = readJson(join(SCHEMAS, 'claim.schema.json'))
    const enums = {
      ClaimKind: claimSchema.items.properties.kind.enum,
      ClaimStatus: claimSchema.items.properties.status.enum,
      Tense: claimSchema.items.properties.tense.enum,
      Confidence: claimSchema.items.properties.confidence.enum,
      EvidenceStrength: claimSchema.items.properties.evidenceStrength.enum,
      Surface: claimSchema.items.properties.surfaces.items.enum,
    }
    for (const [name, values] of Object.entries(enums)) {
      for (const v of values) {
        if (!new RegExp(`'${v}'`).test(types)) {
          fail('C14', 'lib/corpus/types.ts', `type ${name} is missing the schema member '${v}'`)
        }
      }
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C11 — staleness. WARNS by default; fails only under --strict.
   Staleness is a maintenance signal, not a correctness one, and a maintenance
   signal that blocks a deploy gets switched off.
   ═══════════════════════════════════════════════════════════════════════════ */

const today = new Date()
const daysBetween = (isoA, isoB) =>
  Math.floor((new Date(isoB) - new Date(isoA)) / (1000 * 60 * 60 * 24))

for (const c of data.claims) {
  const age = daysBetween(c.lastReviewed, today.toISOString().slice(0, 10))
  if (age > c.reviewEvery) {
    warn('C11', `claims.json#${c.id}`, `last reviewed ${age} days ago; reviewEvery is ${c.reviewEvery}`)
  }
}
for (const s of data.sources) {
  if (!s.lastChecked) continue
  const age = daysBetween(s.lastChecked, today.toISOString().slice(0, 10))
  if (age > 180) warn('C11', `sources.json#${s.id}`, `lastChecked was ${age} days ago`)
}
if (!snapshot) {
  warn('C11', 'data/corpus/fischer-snapshot.json', 'is missing. Run `node scripts/corpus-refresh-fischer.mjs` on a machine that has the lab database.')
} else {
  const age = daysBetween(snapshot.generatedAt, today.toISOString().slice(0, 10))
  const tightest = Math.min(
    ...data.claims.filter((c) => c.subject === 'rol:fischer-rde').map((c) => c.reviewEvery)
  )
  if (age > tightest) {
    warn(
      'C11',
      'data/corpus/fischer-snapshot.json',
      `is ${age} days old; the tightest barn-owl claim wants a review every ${tightest} days. Re-run \`node scripts/corpus-refresh-fischer.mjs\`. (Warning only: that database lives outside this repository and CI cannot reach it.)`
    )
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C8 / C9 over the built output — only with --built
   ═══════════════════════════════════════════════════════════════════════════ */

const OWNED_IN_PUBLIC_DOCS = ['public/docs/resume_content.html']

function builtHtmlFiles() {
  const roots = [join(ROOT, '.next', 'server', 'app'), join(ROOT, 'out')]
  const files = roots.flatMap((r) => walk(r, ['.html']))
  for (const owned of OWNED_IN_PUBLIC_DOCS) {
    const p = join(ROOT, owned)
    if (existsSync(p)) files.push(p)
  }
  return files
}

/**
 * The one exemption from the numeric gate, and it is deliberately narrow.
 *
 * A generated artifact carries a provenance footer describing the corpus that
 * produced it — how many claims, how many sources, the hash, the date. Those
 * digits are the corpus talking about itself, and they change every time the
 * corpus grows. Requiring each of them to be licensed by a claim would either
 * fail on every edit or push a maintainer into padding the allowlist, and a
 * padded allowlist is the failure mode this whole gate exists to prevent.
 *
 * So the region is marked in the markup, where a reviewer can see it, rather
 * than special-cased by filename where nobody would. Two constraints keep it
 * from becoming a hiding place:
 *   - only C8 skips it; the retraction gate C9 still reads every character
 *   - a file that uses the marker must be a generated file (checked below)
 */
const NO_SCAN = /<!--\s*corpus:no-scan\s*-->[\s\S]*?<!--\s*\/corpus:no-scan\s*-->/g

/** Visible text only: scripts, styles, comments, attributes and JSON-LD removed. */
function visibleText(html, { stripNoScan = false } = {}) {
  return (stripNoScan ? html.replace(NO_SCAN, ' ') : html)
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&[a-z]+;/gi, ' ')
    .replace(/\s+/g, ' ')
}

const NUM = /(?<![\w.])[+-]?\$?\d[\d,]*(?:\.\d+)?%?(?![\w])/g

/** "660,000+", "660K+", "$30.4M", "+20.7%" all normalise to a comparable key. */
function normaliseNumber(tok) {
  let t = String(tok).replace(/[$,+%\s]/g, '').toLowerCase()
  if (/^\d+(\.\d+)?k$/.test(t)) t = String(parseFloat(t) * 1000)
  else if (/^\d+(\.\d+)?m$/.test(t)) t = String(parseFloat(t) * 1000000)
  if (/^\d+\.0+$/.test(t)) t = String(parseFloat(t))
  return t
}

if (BUILT) {
  const files = builtHtmlFiles()
  if (!files.length) {
    warn('C8', '--built', 'found no emitted HTML under .next/server/app or out/. Run the build first, or this pass proves nothing.')
  }

  const licensed = new Set()
  for (const c of data.claims) {
    if (!c.asserted || c.kind !== 'metric') continue
    if (!c.surfaces.includes('page') && !c.surfaces.includes('resume')) continue
    for (const n of c.value.numbers) licensed.add(normaliseNumber(n))
  }
  const allowed = new Set(data.allowedNumbers.map((a) => normaliseNumber(a.value)))

  for (const file of files) {
    const rel = relative(ROOT, file)
    const html = readFileSync(file, 'utf8')

    // C9 reads everything, including any no-scan region: an exemption from the
    // numeric gate is not an exemption from the retraction gate.
    scanForRetractions(rel, visibleText(html))

    if (NO_SCAN.test(html)) {
      NO_SCAN.lastIndex = 0
      if (!html.includes('GENERATED FILE')) {
        fail(
          'C8',
          rel,
          'uses the corpus:no-scan marker but is not a generated file. That marker exempts a region from the numeric gate and exists only for a generator\'s own provenance footer; hand-authored copy may not opt out of the gate.'
        )
      }
    }
    NO_SCAN.lastIndex = 0

    const text = visibleText(html, { stripNoScan: true })

    for (const m of text.matchAll(NUM)) {
      const key = normaliseNumber(m[0])
      if (licensed.has(key) || allowed.has(key)) continue
      const context = text.slice(Math.max(0, m.index - 40), m.index + 40).trim()
      fail(
        'C8',
        rel,
        `renders "${m[0]}", which no claim licenses — "…${context}…". Either add it to the claim's value.numbers with a source, or add it to data/corpus/allowed-non-claim-numbers.json with a reason.`
      )
    }
  }

  // The résumé PDF is the highest-traffic résumé surface on the domain, and it is
  // the one artifact this corpus does not generate. It gets the retraction scan
  // anyway, over its extracted text.
  const pdf = join(ROOT, 'public', 'docs', 'Resume.pdf')
  if (existsSync(pdf)) {
    let text = null
    try {
      const { execFileSync } = await import('node:child_process')
      text = execFileSync('pdftotext', [pdf, '-'], { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 })
    } catch {
      warn('C9', 'public/docs/Resume.pdf', 'could not be scanned: `pdftotext` is not on PATH. Install poppler-utils, or the résumé recruiters actually download stays outside the gates.')
    }
    if (text !== null) {
      const before = failures.length
      scanForRetractions('public/docs/Resume.pdf (extracted text)', text)
      if (failures.length > before) {
        // Say what to do, not just what is wrong. This is the one gated artifact
        // the corpus does not yet own, and a failure with no next step is how a
        // gate earns a reputation for crying wolf.
        failures[failures.length - 1].msg +=
          '\n      FIX: `node scripts/gen-resume.mjs --pdf` regenerates this PDF from the corpus via headless Chrome.' +
          '\n      It is not run automatically because overwriting this file changes a byte size the URL harness asserts;' +
          '\n      land the two together. Preview first with `--pdf --pdf-out /tmp/preview.pdf`.'
      }
    }
  } else {
    warn('C9', 'public/docs/Resume.pdf', 'not found; skipping the PDF retraction scan.')
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   C15 — image provenance: where a published picture came from, and what the
   page is allowed to say about it.
   ───────────────────────────────────────────────────────────────────────────
   Every other artifact record points OUTWARD at something a reader can open.
   An artifact with a `provenance` block is different: the site REPRODUCES it.
   Two things can go wrong that no other check would notice.

     1. RIGHTS. The page publishes a work whose origin nobody has stated.
     2. THE UNSTATED CLAIM. A picture is an assertion about what a place looks
        like. An AI-generated image of a real, named campus, published
        unlabelled, is exactly the class of unsourced claim this corpus exists
        to make unreachable — and it would sit in the page's first band, above
        the sentence promising that every claim traces to a source.

   The gate is deliberately asymmetric, because the two failure modes are not
   symmetric:

     · assets on disk + status pending-owner  → WARN, loudly, with the exact
       questions. The owner is allowed to look at the hero before answering
       them; a build that refuses to run would just get the check deleted.
     · status verified + a caption the licence or the disclosure rule requires
       + that caption absent from the built page → FAIL. Once the answer is in,
       shipping the image without the line it obliges is a rights breach, not a
       matter of taste.
     · status blocked + assets still on disk → FAIL. That is the answer coming
       back "no".

   NO ASSETS ON DISK IS A CLEAN PASS. The photograph is progressive enhancement
   over a hero that already works; the absent state is the normal state.
   ═══════════════════════════════════════════════════════════════════════════ */

/** Informational lines printed under PASSED. Declared here because C15 adds to it. */
const orphanReport = []

const IMAGE_EXTS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.avif', '.gif', '.svg'])

/**
 * Origins that owe the reader a line, as a SET rather than an equality test.
 * `ai-generated-composite` is the hero's actual origin — the owner synthesized
 * one image out of several — and a check written as `origin === 'ai-generated'`
 * would have silently stopped applying the moment that narrower value was
 * recorded. The failure mode of an enum widened past its guard is that the
 * guard passes, which is the worst kind.
 */
const SYNTHETIC_ORIGINS = new Set(['ai-generated', 'ai-generated-composite'])

/**
 * Which files of this artifact are actually on disk right now — the master at
 * any of its declared source paths, plus every image in the generated asset
 * directory. Non-images there (the README that documents the pipeline) are not
 * assets: a directory holding only its own documentation has shipped nothing.
 */
function assetsOnDisk(prov) {
  const found = []
  for (const p of prov.sourcePaths ?? []) {
    if (existsSync(join(ROOT, p))) found.push(p)
  }
  if (prov.assetDir) {
    const dir = join(ROOT, prov.assetDir)
    if (existsSync(dir)) {
      let entries = []
      try {
        entries = readdirSync(dir, { withFileTypes: true })
      } catch {
        entries = []
      }
      for (const e of entries) {
        if (!e.isFile() || e.name.startsWith('.')) continue
        if (!IMAGE_EXTS.has(extname(e.name).toLowerCase())) continue
        found.push(`${prov.assetDir}/${e.name}`)
      }
    }
  }
  return found
}

for (const a of data.artifacts) {
  const prov = a.provenance
  if (!prov) continue
  const where = `artifacts.json#${a.id}/provenance`

  /* — references resolve, and the affiliation is a claim, not an adjective — */

  refs(where, prov.sources, 'src', 'provenance.sources')
  refs(where, [prov.affiliationBasis], 'clm', 'provenance.affiliationBasis')
  const basis = claimById.get(prov.affiliationBasis)
  if (basis && !basis.asserted) {
    fail('C15', where, `affiliationBasis ${prov.affiliationBasis} is asserted:false — the record that bounds what may be implied about the institution cannot itself be one we decline to state`)
  }
  if (basis && !basis.surfaces.includes('page')) {
    fail('C15', where, `affiliationBasis ${prov.affiliationBasis} is not licensed for the "page" surface, so the disclaimer it grounds could never be rendered beside the image`)
  }
  checkVerificationPath(where, prov.verificationPath)

  /* — the status invariants — */

  const needsCaption = prov.captionRule === 'attribution' || prov.captionRule === 'disclosure'

  if (prov.status === 'pending-owner') {
    if (prov.origin !== 'unknown') {
      fail('C15', where, `status is "pending-owner" but origin is "${prov.origin}". An unanswered provenance record states ignorance; it does not carry a best guess.`)
    }
    if (prov.attributionRequired !== null) {
      fail('C15', where, 'status is "pending-owner" but attributionRequired is not null. `false` asserts that no credit is owed — which is precisely the assertion an unanswered record may not make.')
    }
    if (prov.rightsBasis !== null) {
      fail('C15', where, 'status is "pending-owner" but rightsBasis is set. Record the basis only once the owner has stated it.')
    }
    if (prov.captionRule !== 'pending' || prov.captionText !== null) {
      fail('C15', where, `status is "pending-owner", so captionRule must be "pending" and captionText null (found "${prov.captionRule}"). While provenance is open the page says nothing about the image at all.`)
    }
    if (prov.verifiedOn !== null) {
      fail('C15', where, 'status is "pending-owner" but verifiedOn is set — nothing has been verified')
    }
    if (!prov.openQuestions.length) {
      fail('C15', where, 'status is "pending-owner" with no openQuestions. A pending record whose question nobody wrote down never gets closed.')
    }
  }

  if (prov.status === 'verified') {
    if (prov.origin === 'unknown') {
      fail('C15', where, 'status is "verified" but origin is still "unknown"')
    }
    if (!prov.rightsBasis) {
      fail('C15', where, 'status is "verified" with no rightsBasis — say in words what makes publishing this lawful')
    }
    if (typeof prov.attributionRequired !== 'boolean') {
      fail('C15', where, 'status is "verified" but attributionRequired is null — the answer is now known, so record it')
    }
    if (!prov.verifiedOn) {
      fail('C15', where, 'status is "verified" with no verifiedOn date')
    }
    if (prov.captionRule === 'pending') {
      fail('C15', where, 'status is "verified" but captionRule is still "pending" — decide whether the page owes a caption')
    }
    if (SYNTHETIC_ORIGINS.has(prov.origin) && prov.captionRule !== 'disclosure') {
      fail('C15', where, `origin is "${prov.origin}" and captionRule is not "disclosure". A synthetic image of a real, named place published without saying so is an unstated claim, and this page argues that it does not make those.`)
    }
    // The record's own verdict and the rule it implies, checked against each
    // other rather than trusted to agree. Two fields that must not drift is
    // the whole reason both exist.
    if (prov.disclosureRequired === true && prov.captionRule !== 'disclosure') {
      fail('C15', where, `disclosureRequired is true but captionRule is "${prov.captionRule}", so nothing renders. The record contradicts itself.`)
    }
    if (prov.disclosureRequired === false && SYNTHETIC_ORIGINS.has(prov.origin)) {
      fail('C15', where, `origin is "${prov.origin}" but disclosureRequired is false. A synthetic depiction of a real place is exactly the case that owes the reader a line.`)
    }
    if (prov.attributionRequired === true && !needsCaption) {
      fail('C15', where, `attributionRequired is true but captionRule is "${prov.captionRule}" — a required credit has to reach the page as a caption`)
    }
    if (needsCaption && !prov.captionText) {
      fail('C15', where, `captionRule is "${prov.captionRule}" but captionText is null. The line is written here, by a human, in advance — never assembled at render time.`)
    }
  }

  /* — an unresolved record may not be offered as evidence — */

  if (prov.status !== 'verified' && (a.url !== null || a.access === 'public')) {
    fail('C15', `artifacts.json#${a.id}`, `provenance is "${prov.status}", so this artifact must carry url:null and an access other than "public". Rendering the image as decoration is allowed; offering it as something a reader may open and cite is not.`)
  }

  /* — what is actually on disk — */

  const onDisk = assetsOnDisk(prov)

  if (!onDisk.length) {
    orphanReport.push(
      `${a.id}: no image files on disk (checked ${prov.sourcePaths.join(', ')}` +
        (prov.assetDir ? ` and ${prov.assetDir}/` : '') +
        `). The hero falls back to its flat ground, which is the shipped state today.`
    )
    continue
  }

  if (prov.status === 'blocked') {
    fail(
      'C15',
      where,
      `provenance is "blocked" — the image may not ship — but ${onDisk.length} file(s) are still on disk: ${onDisk.join(', ')}. Delete them.`
    )
    continue
  }

  if (prov.status === 'pending-owner') {
    warn(
      'C15',
      where,
      [
        `⚠  ${onDisk.length} image file(s) are on disk while this image's PROVENANCE IS UNANSWERED.`,
        `      Files: ${onDisk.join(', ')}`,
        '',
        '      Previewing is fine. PUBLISHING is not: nobody has stated where this image came from,',
        `      and the page pairs it with an institution's marks. Until ${prov.sources.join(', ')} carries an`,
        '      answer, nothing may be asserted about the picture — no caption, no alt text describing it,',
        '      no claim about what it shows. The accessor (lib/corpus/hero-asset.ts) enforces that at render',
        '      time; this warning exists so the open question is visible on every single build.',
        '',
        '      THE QUESTIONS THE OWNER MUST ANSWER:',
        ...prov.openQuestions.map((q, i) => `        ${i + 1}. ${q}`),
      ].join('\n')
    )
  }

  /* — a required caption must actually reach the page — */

  if (prov.status === 'verified' && needsCaption && prov.captionText) {
    const wanted = prov.captionText.replace(/\s+/g, ' ').trim()
    if (!BUILT) {
      warn(
        'C15',
        where,
        `captionRule is "${prov.captionRule}" and the assets are on disk, but this pass cannot see the rendered page. Run \`node scripts/verify-corpus.mjs --built\` after \`npm run build\` — that is the pass that proves the caption shipped.`
      )
    } else {
      const html = builtHtmlFiles()
      const rendered = html.some((f) =>
        visibleText(readFileSync(f, 'utf8')).replace(/\s+/g, ' ').includes(wanted)
      )
      if (!html.length) {
        warn('C15', where, 'no emitted HTML found, so the caption check proved nothing. Run the build first.')
      } else if (!rendered) {
        fail(
          'C15',
          where,
          `captionRule is "${prov.captionRule}" and the image is on disk, but the required line is not in any built page:\n` +
            `      "${wanted}"\n` +
            '      This is the obligation the provenance answer created. Render it through ' +
            'lib/corpus/hero-asset.ts (heroCaption()) rather than retyping it, so the two cannot drift.'
        )
      }
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   Orphan report — informational, never a failure
   ═══════════════════════════════════════════════════════════════════════════ */

{
  const carried = new Set(data.claims.flatMap((c) => c.concepts))
  const orphanConcepts = data.concepts.filter((c) => !carried.has(c.id))
  if (orphanConcepts.length) {
    orphanReport.push(
      `concepts carried by no claim: ${orphanConcepts.map((c) => c.id).join(', ')} ` +
        `(intentional when the concept exists only to route a posting's term to a written gap)`
    )
  }
  const gapConcepts = new Set(data.gaps.flatMap((g) => g.concepts))
  const unreachableGaps = data.gaps.filter((g) => g.concepts.length === 0)
  if (unreachableGaps.length) {
    orphanReport.push(
      `gaps reachable only by an explicit topic guard: ${unreachableGaps.map((g) => g.id).join(', ')}`
    )
  }
  void gapConcepts
}

/* ═══════════════════════════════════════════════════════════════════════════
   Write meta.json — hash, counts, timestamp
   ═══════════════════════════════════════════════════════════════════════════ */

function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`
  if (value && typeof value === 'object') {
    return `{${Object.keys(value)
      .sort()
      .map((k) => `${JSON.stringify(k)}:${canonical(value[k])}`)
      .join(',')}}`
  }
  return JSON.stringify(value)
}

if (failures.length === 0) {
  const hash = createHash('sha256')
  for (const [key, file] of Object.entries(FILES)) {
    if (key === 'meta') continue
    hash.update(file).update(canonical(data[key]))
  }
  if (snapshot) hash.update('fischer-snapshot.json').update(canonical(snapshot))

  const meta = {
    version: data.meta.version,
    generatedAt: today.toISOString().slice(0, 10),
    corpusHash: `sha256:${hash.digest('hex').slice(0, 32)}`,
    counts: {
      claims: data.claims.length,
      metrics: data.claims.filter((c) => c.kind === 'metric').length,
      caveats: data.claims.filter((c) => c.kind === 'caveat').length,
      narratives: data.claims.filter((c) => c.kind === 'narrative').length,
      sources: data.sources.length,
      roles: data.roles.length,
      artifacts: data.artifacts.length,
      concepts: data.concepts.length,
      skills: data.skills.length,
      gaps: data.gaps.length,
      disputes: data.disputes.length,
      unresolvedDisputes: data.disputes.filter((d) => d.resolution === 'unresolved').length,
      retractions: data.retractions.length,
      roleProfiles: data.roleProfiles.length,
    },
    note: data.meta.note,
  }
  writeFileSync(join(CORPUS, 'meta.json'), JSON.stringify(meta, null, 2) + '\n')
  data.meta = meta
}

/* ═══════════════════════════════════════════════════════════════════════════
   Report
   ═══════════════════════════════════════════════════════════════════════════ */

function report() {
  const mode = BUILT ? 'built output + source' : 'source'
  if (!QUIET) {
    console.log(`\nverify-corpus — scanning ${mode}${STRICT ? ', --strict' : ''}\n`)
  }

  if (failures.length) {
    console.error(`FAILED — ${failures.length} problem(s):\n`)
    const grouped = new Map()
    for (const f of failures) {
      if (!grouped.has(f.check)) grouped.set(f.check, [])
      grouped.get(f.check).push(f)
    }
    for (const [check, list] of [...grouped].sort()) {
      console.error(`  ${check}`)
      for (const f of list) console.error(`    ${f.where}\n      ${f.msg}`)
      console.error('')
    }
  }

  if (warnings.length && !QUIET) {
    console.log(`${warnings.length} warning(s):\n`)
    for (const w of warnings) console.log(`  ${w.check}  ${w.where}\n      ${w.msg}`)
    console.log('')
  }

  if (!failures.length && !QUIET) {
    const c = data.meta?.counts ?? {}
    console.log('PASSED')
    console.log(
      `  ${c.claims} claims (${c.metrics} metric, ${c.caveats} caveat, ${c.narratives} narrative) · ` +
        `${c.sources} sources · ${c.roles} roles · ${c.artifacts} artifacts`
    )
    console.log(
      `  ${c.concepts} concepts · ${c.skills} skills · ${c.gaps} gaps · ` +
        `${c.disputes} disputes (${c.unresolvedDisputes} unresolved) · ${c.retractions} retractions`
    )
    console.log(`  corpusHash ${data.meta.corpusHash}`)
    for (const line of orphanReport) console.log(`  note: ${line}`)
    console.log('')
  }
}

report()

if (failures.length) process.exit(1)
if (STRICT && warnings.length) {
  console.error('--strict: warnings are failures on a release tag.')
  process.exit(1)
}
